//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionVentaLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiasprimas
    {
        public materiasprimas()
        {
            this.productosmp = new HashSet<productosmp>();
        }
    
        public int idmateriaprima { get; set; }
        public string materiaprima { get; set; }
    
        public virtual ICollection<productosmp> productosmp { get; set; }
    }
}
