//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionVentaLINQ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ventaEntities : DbContext
    {
        public ventaEntities()
            : base("name=ventaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<materiasprimas> materiasprimas { get; set; }
        public DbSet<medidas> medidas { get; set; }
        public DbSet<productos> productos { get; set; }
        public DbSet<productosmp> productosmp { get; set; }
        public DbSet<productospack> productospack { get; set; }
        public DbSet<tipos> tipos { get; set; }
    }
}
