//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionVentaLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public productos()
        {
            this.productosmp = new HashSet<productosmp>();
            this.productospack = new HashSet<productospack>();
            this.productospack1 = new HashSet<productospack>();
        }
    
        public int idproducto { get; set; }
        public Nullable<int> idtipo { get; set; }
        public Nullable<int> idmedida { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> borrado { get; set; }
    
        public virtual medidas medidas { get; set; }
        public virtual tipos tipos { get; set; }
        public virtual ICollection<productosmp> productosmp { get; set; }
        public virtual ICollection<productospack> productospack { get; set; }
        public virtual ICollection<productospack> productospack1 { get; set; }
    }
}
