//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionVentaLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class productospack
    {
        public int idproductocompuesto { get; set; }
        public int idproductosimple { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual productos productos1 { get; set; }
    }
}
